@RestaurantAPI_HostAddress = https://localhost:44320/

### GetAllRestaurants()
GET {{RestaurantAPI_HostAddress}}/api/restaurant/
Accept: application/json
###

### GetRestaurantByIdRoute()
GET {{RestaurantAPI_HostAddress}}/api/restaurant/8
Accept: application/json
###

### GetRestaurantByIdQuery()
GET {{RestaurantAPI_HostAddress}}/api/restaurant/GetRestaurantById?id=7
Accept: application/json
###

### CreateRestaurant()
### There must be a blank line separating headers from the body
### The structure is: Request line → Headers → Blank line → Body
POST {{RestaurantAPI_HostAddress}}/api/restaurant/
Content-Type: application/json
Accept: application/json

{
  "name": "Pizza Poznan4",
  "description": "desc",
  "category": "pizza",
  "email": "piz@gmail.com",
  "phoneNumber": "2332323",
  "hasDelivery": false,
  "city": "Krakow",
  "street": "Main street",
  "zipCode": "32-222"
}
###

### UpdateRestaurant()
PUT {{RestaurantAPI_HostAddress}}/api/restaurant/6
Content-Type: application/json
Accept: application/json

{
  "name": "Pizza Poznan Updated2",
  "description": "desc Updated2",
  "hasDelivery": true
}
###

### DeleteRestaurant()
DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/7
Accept: application/json
###

### GetAllDishes()
GET {{RestaurantAPI_HostAddress}}/api/restaurant/1/dish
Accept: application/json
###

### GetDishByIdRoute()
GET {{RestaurantAPI_HostAddress}}/api/restaurant/1/Dish/2
Accept: application/json
###

### GetDishByIdQuery()
GET {{RestaurantAPI_HostAddress}}/api/restaurant/1/Dish/GetDishById?dishId=2
Accept: application/json
###

### CreateDish()
### There must be a blank line separating headers from the body
### The structure is: Request line → Headers → Blank line → Body
POST {{RestaurantAPI_HostAddress}}/api/restaurant/1/Dish
Content-Type: application/json
Accept: application/json

{
  "name": "Poznan Hamburger",
  "description": "Best hamburger in the town",
  "price": 10
}
###

### UpdateDish()
PUT {{RestaurantAPI_HostAddress}}/api/restaurant/1/Dish/2
Content-Type: application/json
Accept: application/json

{
  "name": "Poznan Hamburger Updated",
  "description": "Best hamburger in the town Updated",
  "price": 67
}
###

### DeleteAllDishesByRestaurantId()
DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/2/Dish/DeleteAllDishesByRestaurantId
Accept: application/json
###

### DeleteDish()
DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/1/Dish/13
Accept: application/json
###
